#!/usr/bin/env python3
# =============================================================================
# Script:      GetSeqsFromFasta.py
# Description: Extracts sequences from a multifasta file based on a list of
#              sequence IDs. Matching is performed on the record ID (the
#              portion of the FASTA header before the first whitespace).
#
# Usage:
#   python GetSeqsFromFasta.py \
#       --multifasta <database.fasta> \
#       --ids        <ids.txt> \
#       --output     <extracted.fasta>
#
# Arguments:
#   --multifasta   Path to the input multifasta database.
#   --ids          Path to a text file with one sequence ID per line.
#   --output       Path for the output FASTA file.
#
# Example:
#   python GetSeqsFromFasta.py \
#       --multifasta dbseq/HormoneDB/hormoneDB.fasta \
#       --ids        temp/ids/cytokinin_ids.txt \
#       --output     output/hormone/cytokinin/cytokinin_sequences.fasta
#
# Notes:
#   - IDs in the text file must match the record.id field exactly (i.e., the
#     header text up to the first space).
#   - The output directory is created automatically if it does not exist.
#   - Sequences not found in the database are silently skipped; check that
#     IDs were generated by the same pipeline step that built the database.
#
# Dependencies: biopython (Bio.SeqIO)
# =============================================================================

import os
import argparse
import logging
from Bio import SeqIO

logging.basicConfig(format='%(levelname)s: %(message)s', level=logging.INFO)


def parse_args():
    parser = argparse.ArgumentParser(
        description="Extract sequences from a multifasta file by sequence ID."
    )
    parser.add_argument("--multifasta", required=True,
                        help="Path to the input multifasta database.")
    parser.add_argument("--ids", required=True,
                        help="Path to the ID list file (one ID per line).")
    parser.add_argument("--output", required=True,
                        help="Path for the output FASTA file.")
    return parser.parse_args()


def extract_sequences(multifasta_file: str, ids_file: str, output_file: str) -> None:
    # Load target IDs into a set for O(1) lookup
    try:
        with open(ids_file) as fh:
            target_ids = {line.strip() for line in fh if line.strip()}
    except OSError as exc:
        logging.error(f"Cannot read ID file: {exc}")
        return

    found = 0
    try:
        with open(output_file, "w") as out_fh:
            for record in SeqIO.parse(multifasta_file, "fasta"):
                if record.id in target_ids:
                    SeqIO.write(record, out_fh, "fasta")
                    found += 1
    except OSError as exc:
        logging.error(f"Error processing multifasta file: {exc}")
        return

    if found == 0:
        logging.warning(
            "No sequences matched the provided IDs. "
            "Verify that IDs were generated by the same pipeline step "
            "that built the database (prepare_blastdb.sh)."
        )
    else:
        logging.info(f"{found} sequence(s) extracted → {output_file}")


def main():
    args = parse_args()

    for path in [args.multifasta, args.ids]:
        if not os.path.exists(path):
            logging.error(f"File not found: '{path}'")
            return

    output_dir = os.path.dirname(args.output)
    if output_dir:
        os.makedirs(output_dir, exist_ok=True)

    extract_sequences(args.multifasta, args.ids, args.output)
    logging.info("Extraction complete.")


if __name__ == "__main__":
    main()
